### ISSUE TITLE
What issues did toggle mute cause?

### ISSUE THREAD

**Issue by C0mputery** [Adler-real/Better_ContentWarning#2]
I made toggle mute, and I've not had any issues reported to me. If I could get something I could at least try to fix it.

**Comment by Adler-real** [comment]
Oh hey! I just try it again. And I noticed that the push-to-talk mode was active and that's why it "didn't work". I will add the mod again immediately. Sorry! I'm stupid

I love your mod

**Comment by C0mputery** [comment]
np, np. I was just super worried when I saw that.
