### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by friskin69** [Adler-real/Better_ContentWarning#6]
![image](https://github.com/Adler-real/Better_ContentWarning/assets/125573012/1f639f22-d023-4051-9655-7c0d99f09b78)
we cannot play more with that modpack because bug with extract video

**Comment by friskin69** [comment]
its not purchased camera

**Comment by Adler-real** [comment]
Oh ok, it could be because of the Content Warning update that a mod has problems with it. I will check that.

Thank you for opening a issue to help the Modpack 🧡️

**Comment by Adler-real** [comment]
Hey, it's because of Flashcards, could you remove the mod and then try if it works for you? I will publish the update later today, Thanks!

**Comment by friskin69** [comment]
[content_warning_5004c428.webm](https://github.com/Adler-real/Better_ContentWarning/assets/125573012/cb6df1ad-baf4-4ba3-928c-6b569884bb76)
Yea all work, thanks!
