### ISSUE TITLE
When inserting disc into TV it dissapears

### ISSUE THREAD

**Issue by ikonikfan** [Adler-real/Better_ContentWarning#7]
When you go to put the disc into the tv to play it, sometimes the disc will disappear but not play the camera footage

**Comment by Adler-real** [comment]
Hey, can you give me the mod list so I can check if the right mods are installed? And it would be helpful to know which modpack and game version you are using.

_Thank you for opening a issue to help the Modpack 🧡️_

**Comment by ikonikfan** [comment]
Game version: 1.17.b
Modpack: https://thunderstore.io/c/content-warning/p/Horizon/Better_Content_Warning_Modpack/
The only mods ive been using is within the mod pack, no other mods was installed

**Comment by Adler-real** [comment]
I would like to know the modpack version, is it 2.2.4? Because a similar problem should actually be fixed in 2.2.4.

If the mod "Flashcard" is there, please **create a new profile and install the latest version of the modpack**, because flashcards are causing problems.

(I wanted to know the mod list, because the mod manager r2modman, (and i think Thunderstore) **does not delete mods on a update**, and i wanted to double check it)

**Comment by ikonikfan** [comment]
yeah the version is 2.2.4

**Comment by Adler-real** [comment]
Ok, i will check that, but that takes time, it's not easy to fix.
but it is not the camera you bought, its the default camera?

(but the mod "Flashcard" is not in the modpack?)

**Comment by ikonikfan** [comment]
Default camera and yes the Flashcard mod is not in the modpack

**Comment by friskin69** [comment]
yea i have too that bug, with disk dissapears.

**Comment by Adler-real** [comment]
I'm sorrry it's taking so long, I don't have much time at the moment. And since I'm a Linux user, it takes a while to start content warning since the last update, even without mods. i dont know why.

**Comment by Adler-real** [comment]
Hi again, I'm very sorry this took so long, but now CW is working/starting again, so now I can test it. If you want to see the "progress" you can check [Here](https://github.com/users/Adler-real/projects/2). I hope I find the problem. Sorry guys.

https://github.com/users/Adler-real/projects/2

**Comment by allferno** [comment]
I found the reason why the disk is missing with some probability. The reason was the "more comments" mod. If you remove it from the modpack, everything will work

**Comment by Adler-real** [comment]
Thank you all, and thanks to @allferno! The update is out!
